### ISSUE TITLE
[2.0] Roadmap

### ISSUE THREAD

**Issue by woozyking** [EQWorks/react-labs#146]
- [ ] utilize github releases in place of manually updated CHANGELOG.md. like what's done in lumen-table (#145)
- [ ] complex components (ones that require compositions and/or custom workflow/business logic) to be dissected out in similar fashion as lumen-table (example such as the image slider and list)
- [ ]base components to be groomed over to be simplified (such as reducing the amount of redundant props that are already MUI "native")
- [ ] base components that are solidly simplified and revised to ensure basic test coverage (at least rendering test) and package into lumen-ui
- [ ] see where we can separate functional and styling aspects as much as we can to make things work without having the issues we've had before
